# Generated by Django 4.2.2 on 2023-07-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='main_app.make')),
            ],
        ),
    ]
